function time_manager(){var O='bootstrap',P='begin',Q='gwt.codesvr.time_manager=',R='gwt.codesvr=',S='time_manager',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='Failed to load ',ob='head',pb='meta',qb='name',rb='time_manager::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='time_manager.nocache.js',Ib='base',Jb='//',Kb='supportsDateTimeInput',Lb='input',Mb='type',Nb='datetime',Ob='text',Pb='y',Qb='n',Rb='user.agent',Sb='webkit',Tb='safari',Ub='msie',Vb=10,Wb=11,Xb='ie10',Yb=9,Zb='ie9',$b=8,_b='ie8',ac='gecko',bc='gecko1_8',cc=2,dc=3,ec=4,fc='selectingPermutation',gc='time_manager.devmode.js',hc='088E44170A8F09CE8F1DF836948CD4D2',ic=':1',jc='221D19000F997CB666828FFF7033CFF5',kc='293DFDFDEA8857DEB39D2B71B05B2195',lc='439E7C8AD1F79D4CCD3B5196DEECD0DD',mc='72E837AA96E9601F96A672CEC6F69663',nc='8E2070F2016ED5D4EA01AD2D659D93B1',oc=':',pc='.cache.js',qc='link',rc='rel',sc='stylesheet',tc='href',uc='loadExternalRefs',vc='gwt/clean/clean.css',wc='gwt/chrome/chrome.css',xc='timebox.css',yc='end',zc='http:',Ac='file:',Bc='_gwt_dummy_',Cc='__gwtDevModeHook:time_manager',Dc='Ignoring non-whitelisted Dev Mode URL: ',Ec=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
time_manager.__sendStats=r;time_manager.__moduleName=S;time_manager.__errFn=null;time_manager.__moduleBase=U;time_manager.__softPermutationId=V;time_manager.__computePropValue=null;time_manager.__getPropMap=null;time_manager.__installRunAsyncCode=function(){};time_manager.__gwtStartLoadingFragment=function(){return null};time_manager.__gwt_isKnownPropertyValue=function(){return false};time_manager.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};time_manager.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[time_manager.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
time_manager.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(time_manager.__errFn){n.onerror=function(){time_manager.__errFn(S,new Error(nb+code))}}p.getElementsByTagName(ob)[V].appendChild(n)}
time_manager.__startLoadingFragment=function(a){return D(a)};time_manager.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,bb);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;time_manager.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return time_manager.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Kb]=function(){try{var b=document.createElement(Lb);b.setAttribute(Mb,Nb);return b.type!==Ob?Pb:Qb}catch(a){return Qb}};i[Kb]={n:V,y:W};j[Rb]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(Sb)!=-1}())return Tb;if(function(){return a.indexOf(Ub)!=-1&&(b>=Vb&&b<Wb)}())return Xb;if(function(){return a.indexOf(Ub)!=-1&&(b>=Yb&&b<Wb)}())return Zb;if(function(){return a.indexOf(Ub)!=-1&&(b>=$b&&b<Wb)}())return _b;if(function(){return a.indexOf(ac)!=-1||b>=Wb}())return bc;return bb};i[Rb]={gecko1_8:V,ie10:W,ie8:cc,ie9:dc,safari:ec};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};time_manager.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};time_manager.__computePropValue=k;o.__gwt_activeModules[S].bindings=time_manager.__getPropMap;r(O,fc);if(q()){return D(gc)}var l;try{h([Qb,bc],hc);h([Pb,bc],hc);h([Qb,bc],hc+ic);h([Pb,bc],hc+ic);h([Qb,Zb],jc);h([Pb,Zb],jc);h([Qb,Zb],jc+ic);h([Pb,Zb],jc+ic);h([Qb,Xb],kc);h([Pb,Xb],kc);h([Qb,Xb],kc+ic);h([Pb,Xb],kc+ic);h([Qb,Tb],lc);h([Pb,Tb],mc);h([Qb,_b],nc);h([Pb,_b],nc);h([Qb,_b],nc+ic);h([Pb,_b],nc+ic);l=f[k(Kb)][k(Rb)];var m=l.indexOf(oc);if(m!=-1){g=parseInt(l.substring(m+W),Vb);l=l.substring(V,m)}}catch(a){}time_manager.__softPermutationId=g;return D(l+pc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(qc);b.setAttribute(rc,sc);b.setAttribute(tc,D(a));p.getElementsByTagName(ob)[V].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(uc,P);c(vc);c(wc);c(xc);r(uc,yc)}
B();time_manager.__moduleBase=C();t[S].moduleBase=time_manager.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==zc||o.location.protocol==Ac);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=Bc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=Cc;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(Dc+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+Ec]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,yc);A(H);return true}
time_manager.succeeded=time_manager();